version: 2.1
executors:
  worker:
    docker:
      - image: marvelmathesh/docker:rom
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: SSH
          command: |
            sudo apt install neofetch
            neofetch
            pwd
            cd ..
            pwd
            cd ..
            pwd
            cd tmp
            pwd
            cd rom
            pwd
            
