version: 2.1
executors:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: large
jobs:
  build:
    executor: build
    steps:
      - run:
          name: sex
          command: |
            cd .. && pwd && cd .. && pwd
            cd .. && ls && df -h
            sudo apt install neofetch
            neofetch
