version: 2.1
executors:
  worker:
    docker:
      - image: marvelmathesh/docker:rom
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: SSH
          command: |
            cd ..
            cd ..
            cd tmp && cd rom
            pwd
            mkdir ~/bin
            PATH=~/bin:$PATH
            cd ~/bin && curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
            pwd && mkdir pixel
            git config --global user.name "Subhendu-droid"
            git config --global user.email "maharanasubhendu3@gmail.com"
            cd tmp && cd rom && cd pixel &&  repo init -u https://github.com/PixelExperience/manifest -b twelve
            cd tmp && cd rom && cd pixel && repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
            cd tmp && cd rom && cd pixel && git clone https://github.com/Subhendu-droid/device_asus_X01AD-1.git -b Arrow-12.0 device/asus/X01AD
            cd tmp && cd rom && cd pixel && git clone https://github.com/BCA-RMIT/vendor_asus_X01AD.git -b lineage-18.1 vendor/asus/X01AD
            cd tmp && cd rom && cd pixel && git clone https://github.com/Subhendu-droid/android_kernel_asus_X01AD.git -b lineage-18.1 kernel/asus/X01AD
            cd tmp && cd rom && cd pixel && . build/envsetup.sh
            cd tmp && cd rom && cd pixel && lunch aosp_X01AD-userdebug
            cd tmp && cd rom && cd pixel && mka bacon
            cd out/target/product/X01AD
            curl -sL https://git.io/file-transfer | sh
            ./transfer wet x*zip

            
