version: 2.1
executors:
  worker:
    docker:
      - image: marvelmathesh/docker:rom
jobs:
  build:
    executor: worker
    steps:
      - run:
          name: SSH
          command: |
            mkdir ~/bin
            PATH=~/bin:$PATH
            cd ~/bin && curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
            mkdir xtended
            git config --global user.name "Subhendu-droid"
            git config --global user.email "maharanasubhendu3@gmail.com"
            cd xtended && repo init --depth=1 --no-repo-verify -u https://github.com/Project-Xtended/manifest.git -b xs --groups=all,-notdefault,-device,-darwin,-x86,-mips && git clone https://github.com/Subhendu-droid/local_manifest --depth=1 -b main .repo/local_manifests && repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 
            . build/envsetup.sh
            lunch xteny_X01AD-userdebug
            export ALLOW_MISSING_DEPENDENCIES=true
            export TZ=Asia/Kolkata #put before last build command
            mka bacon
            cd out/target/product/X01AD
            curl -sL https://git.io/file-transfer | sh
            ./transfer wet x*zip
